if (self.CavalryLogger) { CavalryLogger.start_js(["+y9t+Cv"]); }

__d("CometLazyPopoverTrigger.react",["BasePopoverTrigger.react","CometPopoverLoadingState.react","lazyLoadComponent","react","useCometPopoverInteractionTracing"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g,h=g||b("react");function a(a){var c=a.fallback;c=c===void 0?h.jsx(b("CometPopoverLoadingState.react"),{withArrow:!0}):c;var d=a.popoverResource,e=a.preloadTrigger,f=a.tracePolicy;a=babelHelpers.objectWithoutPropertiesLoose(a,["fallback","popoverResource","preloadTrigger","tracePolicy"]);var g=h.useMemo(function(){return b("lazyLoadComponent")(d)},[d]);f=b("useCometPopoverInteractionTracing")(f);return h.jsx(b("BasePopoverTrigger.react"),babelHelpers["extends"]({fallback:c,interactionTracker:f,popover:g,popoverPreloadResource:d,preloadTrigger:e},a))}}),null);
__d("BaseTextInput.react",["BaseFocusRing.react","BaseInput.react","react"],(function(a,b,c,d,e,f){"use strict";var g,h=g||b("react"),i={root:{":disabled":{color:"e70eycc3"}}};function a(a,c){var d=a.suppressFocusRing,e=a.xstyle,f=babelHelpers.objectWithoutPropertiesLoose(a,["suppressFocusRing","xstyle"]);return h.jsx(b("BaseFocusRing.react"),{suppressFocusRing:d,children:function(a){return h.jsx(b("BaseInput.react"),babelHelpers["extends"]({},f,{ref:c,xstyle:[i.root,a,e]}))}})}c=h.memo(h.forwardRef(a));e.exports=c}),null);
__d("processBaseInputValidators",[],(function(a,b,c,d,e,f){"use strict";e.exports=g;function g(a,b){if(typeof b==="function")return[b(a)];var c=[];for(var b=b,d=Array.isArray(b),e=0,b=d?b:b[typeof Symbol==="function"?Symbol.iterator:"@@iterator"]();;){var f;if(d){if(e>=b.length)break;f=b[e++]}else{e=b.next();if(e.done)break;f=e.value}f=f;Array.isArray(f)?c.push.apply(c,g(a,f)):typeof f==="function"&&c.push(f(a))}return c.filter(function(a){return a.type!=="CORRECT"})}}),null);
__d("useBaseInputValidators",["processBaseInputValidators","react","useStable"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g,h=g||b("react");function a(a){var c=a.validator,d=a.value;a=h.useState(!0);var e=a[0];a=a[1];var f=b("useStable")(function(){return d});e&&d!==f&&a(!1);return h.useMemo(function(){var a,f=c!=null&&!e?b("processBaseInputValidators")(d,c):[];if(f.length===0)return{allResults:f,topResultReason:null,topResultType:"CORRECT"};var g=f.some(function(a){return a.type==="ERROR"});a=(a=f.find(function(a){return a.type===(g?"ERROR":"WARN")}))!=null?a:null;return{allResults:f,topResultReason:a!=null&&a.reason!=null?a.reason:null,topResultType:a!=null?a.type:"CORRECT"}},[e,c,d])}}),null);
__d("useCometAlertDialog",["CometCardedDialogLoadingState.react","react","requireDeferred","useCometDeferredDialog"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g,h=g||b("react"),i=b("requireDeferred")("CometAlertDialogImpl.react");function j(){return h.jsx(b("CometCardedDialogLoadingState.react"),{})}function a(){var a=b("useCometDeferredDialog")(i,j),c=a[0];a=a[1];var d=h.useCallback(function(a,b){b===void 0&&(b=function(){}),c(a,b)},[c]);return[d,a]}}),null);
__d("CometFileSelector.react",["react","recoverableViolation"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g,h=g||b("react");function i(a){return a.map(function(a){if(a.indexOf("/")!==-1||a[0]===".")return a;b("recoverableViolation")('Accept parameter "'+a+'" for CometFileSelector is being interpreted as a file extension since it has no slash (/), but file extensions must start with a period (.)',"profile_comet");return"."+a}).join(",")}function a(a){var b=a.accept,c=a.children,d=a.multiple;d=d===void 0?!1:d;var e=a.onFilesSelected,f=h.useRef(null);h.useEffect(function(){var a=f.current;if(a!=null){var b=function(a){a.stopPropagation()};a.addEventListener("click",b);return function(){a.removeEventListener("click",b)}}});a=h.useCallback(function(){f.current!=null&&f.current.click()},[]);var g=h.useCallback(function(a){e(a.currentTarget.files),a.currentTarget.value=""},[e]);return h.jsxs(h.Fragment,{children:[h.jsx("input",{accept:b!=null?i(b):void 0,className:"mkhogb32",multiple:d,onChange:g,ref:f,type:"file"}),c(a)]})}}),null);
__d("createCometAtSignComposerMentionsMatchStrategy",["DocumentMentionsRegex"],(function(a,b,c,d,e,f){"use strict";e.exports=a;c=b("DocumentMentionsRegex").PUNCTUATION;d=["@","\\uff20"].join("");f="[^"+d+c+"\\s]";e="(?:\\.[ |$]| |["+c+"]|)";a=75;var g=new RegExp("(^|\\s|\\()(["+d+"]((?:"+f+e+"){0,"+a+"}))$");b=50;var h=new RegExp("(^|\\s|\\()(["+d+"]((?:"+f+"){0,"+b+"}))$");function a(a){var b=a.minMatchLength;return{findMentionableString:function(a){var c=g.exec(a);c===null&&(c=h.exec(a));if(c!==null){a=c[1];var d=c[3];if(d.length>=b)return{leadOffset:c.index+a.length,matchingString:d,replaceableString:c[2]}}return null},name:"AtSignComposerMentionStrategy("+b.toString()+")"}}}),null);
__d("CometChromeDome",["JSScheduler","requireDeferred"],(function(a,b,c,d,e,f){"use strict";f.init=a;var g=b("requireDeferred")("Chromedome");function a(){g.onReady(function(a){b("JSScheduler").scheduleLoggingPriCallback(function(){a.start({})})})}}),null);
__d("MWChatCrushState.bs",[],(function(a,b,c,d,e,f){"use strict";a=[];b=[];c=[];d=[];e={openTabsState:a,chatHeads:b,forceCollapsedHeads:c,notificationTimers:d};f.none=e}),null);
__d("MWChatMultitabStateHook.bs",["MWChatCrushState.bs","MWChatMultitabContext.bs","MWChatMultitabDispatcher.bs","bs_curry","react"],(function(a,b,c,d,e,f){"use strict";var g,h=g||b("react");function a(a){var c=h.useContext(b("MWChatMultitabContext.bs").context);a=h.useState(function(){if(c!==void 0)return b("MWChatMultitabDispatcher.bs").state(c);else return b("MWChatCrushState.bs").none});var d=a[1];h.useEffect(function(){if(c===void 0)return;var a=b("MWChatMultitabDispatcher.bs").listen(c,function(a){return b("bs_curry")._1(d,function(a){return b("MWChatMultitabDispatcher.bs").state(c)})});return function(c){return b("bs_curry")._1(a,void 0)}},[c,d]);return a[0]}f.useHook_DEPRECATED=a}),null);
__d("useCometMentionsDataSourceResolver",["JSTracing","react"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g,h=g||b("react");function a(a){h.useLayoutEffect(function(){a.forEach(function(a){var c=a.dataSource;b("JSTracing").clear(function(){return c.bootstrap()})})},[a]);return h.useMemo(function(){var b=new Map();return function(c){var d={dataSource:null,searchResult:null};if(c==null)return d;var e=b.get(c);if(e!=null)return e;for(var e=0;e<a.length;e++){var f=a[e],g=f.dataSource;f=f.matchStrategy;f=f.findMentionableString(c);if(f!=null){g={dataSource:g,searchResult:f};b.set(c,g);return g}}b.set(c,d);return d}},[a])}}),null);
__d("cometTypeaheadODSLogFetchCacheEvent",["requireDeferred"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g=b("requireDeferred")("ODS");function a(a,b,c){b===void 0&&(b=!0);c===void 0&&(c=1);if(!b)return;g.onReady(function(b){b.bumpEntityKey(354,a,"fetched-cache",c)})}}),null);
__d("cometTypeaheadODSLogFetchNetworkEvent",["requireDeferred"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g=b("requireDeferred")("ODS");function a(a,b,c){b===void 0&&(b=!0);c===void 0&&(c=1);if(!b)return;g.onReady(function(b){b.bumpEntityKey(354,a,"fetched-network",c)})}}),null);
__d("XUIButton.react",["cx","AbstractButton.react","XUISpinner.react","joinClasses","prop-types","react"],(function(a,b,c,d,e,f,g){var h,i=h||b("react");a="medium";c=function(a){babelHelpers.inheritsLoose(c,a);function c(){var b,c;for(var d=arguments.length,e=new Array(d),f=0;f<d;f++)e[f]=arguments[f];return(b=c=a.call.apply(a,[this].concat(e))||this,c.buttonRef=i.createRef(),b)||babelHelpers.assertThisInitialized(c)}var d=c.prototype;d.focus=function(){this.buttonRef.current!=null&&this.buttonRef.current.focus()};d.render=function(){var a=this.props,c=a.borderShade,d=a.loading,e=a.size,f=a.suppressed,g=a.use;a=babelHelpers.objectWithoutPropertiesLoose(a,["borderShade","loading","size","suppressed","use"]);e="_4jy0"+(e==="small"?" _517i":"")+(e==="medium"?" _4jy3":"")+(e==="large"?" _4jy4":"")+(e==="xlarge"?" _4jy5":"")+(e==="xxlarge"?" _4jy6":"")+(g==="default"?" _517h":"")+(g==="confirm"?" _4jy1":"")+(g==="special"?" _4jy2":"")+(c==="light"?" _51sy":"")+(c==="dark"?" _9c6":"")+(f?" _59pe":"")+(g==="confirm"||g==="special"?" selected":"");return i.jsx(b("AbstractButton.react"),babelHelpers["extends"]({},a,{label:d?i.jsx(b("XUISpinner.react"),{}):this.props.label,className:b("joinClasses")(this.props.className,e),ref:this.buttonRef,disabled:!!this.props.disabled}))};return c}(i.Component);e.exports=c;c.defaultProps={use:"default",size:a,borderShade:"light",suppressed:!1};c.propTypes={use:b("prop-types").oneOf(["default","special","confirm"]),size:b("prop-types").oneOf(["small","medium","large","xlarge","xxlarge"]),borderShade:b("prop-types").oneOf(["light","dark"]),suppressed:b("prop-types").bool,disabled:b("prop-types").bool}}),null);
__d("EmojiFormat.bs",[],(function(a,b,c,d,e,f){"use strict";function g(a){return a.split("_").map(function(a){return parseInt(a,16)})}function a(a){return a.map(function(a){return a.toString(16)}).join("_")}function h(a){return a.map(function(a){return String.fromCodePoint(a)}).join("")}function b(a){return h(g(a))}f.codeStringToCodeArray=g;f.codeArrayToCodeString=a;f.codeArrayToUnicode=h;f.codeStringToUnicode=b}),null);
__d("EmojiLikeConstants",["EmojiStaticConfig"],(function(a,b,c,d,e,f){"use strict";a=b("EmojiStaticConfig").sizeMap;f.sizeMap=a;c=Object.freeze({XSMALL:"xsmall",SMALL:"small",MEDIUM:"medium",LARGE:"large"});f.size=c;d={dp16:"xsmall",dp32:"small",dp64:"medium",db64:"medium",dp128:"large"};f.sizeMapTransfer=d;e=Object.freeze({PICKER:"picker",HOT_LIKE:"hot_like"});f.source=e;b=[983040];f.FB_THUMBS_UP_EMOJI=b;a="hot_emoji_source";f.SOURCE_TAG_PREFIX=a;c="hot_emoji_size";f.TAG_PREFIX_NEW=c;d="emoji_like";f.TAG_PREFIX_OLD=d;e="\ud83d\udc4d";f.THUMBS_UP_EMOJI=e;b=[128077];f.THUMBS_UP_EMOJI_CODES=b}),null);
__d("MessengerMQTTConnectionEvents",[],(function(a,b,c,d,e,f){"use strict";a="messenger-mqtt-delta";f.DELTA_EVENT=a;b="messenger-mqtt-stream-disconnect";f.STREAM_DISCONNECT=b;c="messenger-mqtt-stream-connecting";f.STREAM_CONNECTING=c;d="messenger-mqtt-stream-connect";f.STREAM_CONNECT=d;e="Connected";f.STATE_CONNECTED=e;a="Disconnected";f.STATE_DISCONNECTED=a;b="Connecting";f.STATE_CONNECTING=b;c="messenger-mqtt-typ";f.TYP=c}),null);
__d("MercuryLocalIDs",["randomInt"],(function(a,b,c,d,e,f){"use strict";f.generateThreadID=a;f.generateOfflineThreadingID=g;function a(a){return"root:"+g(a)}function g(a){a=a!=null?a:Date.now();var c=b("randomInt")(0,4294967295);c=("0000000000000000000000"+c.toString(2)).slice(-22);a=a.toString(2)+c;return h(a.slice(-63))}function h(a){var b="";a=a;while(a!="0"){var c=0,d="";for(var e=0;e<a.length;e++)c=2*c+parseInt(a[e],10),c>=10?(d+="1",c-=10):d+="0";b=c.toString()+b;a=d.slice(d.indexOf("1"))}return b}}),null);
__d("Popup",["isTruthy"],(function(a,b,c,d,e,f){f.open=a;function a(a,c,d,e){var f=[];b("isTruthy")(c)&&f.push("width="+c);b("isTruthy")(d)&&f.push("height="+d);var g=document.body;if(g!=null&&c!=null&&c!==0&&d!=null&&d!==0){var h="screenX"in window?window.screenX:window.screenLeft,i="screenY"in window?window.screenY:window.screenTop,j="outerWidth"in window?window.outerWidth:g.clientWidth;g="outerHeight"in window?window.outerHeight:g.clientHeight-22;h=Math.floor(h+(j-c)/2);j=Math.floor(i+(g-d)/2.5);f.push("left="+h);f.push("top="+j)}f.push("scrollbars");return window.open(a,e!=null&&e!==""?e:"_blank",f.join(","))}}),null);
__d("cxMargin",["cx"],(function(a,b,c,d,e,f,g){"use strict";e.exports=a;function a(a){throw new Error("cxMargin: Unexpected margin transformation.")}}),null);
__d("XP2PVerificationDialogBaseControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f){a=b("jsRouteBuilder")("/p2p/verify/dialog/",Object.freeze({is_sender_flow:!1}),void 0);c=a;e.exports=c}),null);
__d("fbjs/lib/shallowEqual",["shallowEqual"],(function(a,b,c,d,e,f){"use strict";e.exports=b("shallowEqual")}),null);
__d("shallowCompare",["fbjs/lib/shallowEqual"],(function(a,b,c,d,e,f){"use strict";e.exports=a;function a(a,c,d){return!b("fbjs/lib/shallowEqual")(a.props,c)||!b("fbjs/lib/shallowEqual")(a.state,d)}}),null);